"""
VeriField Nexus — VM0042 v2.2 & 11 June 2026 C&C Authoritative Equation Matrix
================================================================================
Normative Reference Registry for Agriculture Quantification Phase 3B-3.
Covers:
- VM0042 Section 8.2: Baseline Emissions by Source
- VM0042 Section 8.3: Project Emissions by Source
- VM0042 Section 8.4: Leakage by Source
- VM0042 Section 8.5.1: Carbon Stock Change Completion (Eq. 44, 45, 48, 49)
- VM0042 Section 8.5: Net GHG Quantification (Eq. 37, 38, 39, 40, 41, 42, 43)
- VM0042 Section 8.7: VCU Readiness Deductions & Eligible Quantities (Eq. 75, 76, 77, 78, 79)
"""

from dataclasses import asdict, dataclass
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class EquationDefinition:
    equation_id: str
    name: str
    official_source: str
    version: str
    section: str
    equation_formula: str
    inputs: List[str]
    input_units: Dict[str, str]
    output: str
    output_units: str
    quantification_approach: str
    applicability: str
    production_function: str
    test_vector_ref: str
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


VM0042_EQUATION_MATRIX: List[EquationDefinition] = [
    EquationDefinition(
        equation_id="VM0042_EQ_FOSSIL_FUEL_BSL",
        name="Baseline Emissions from Fossil Fuel Combustion",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.2.1",
        equation_formula="E_ff,bsl,t = sum_f (Fuel_f,bsl,t * EF_f)",
        inputs=["Fuel_f,bsl,t", "EF_f"],
        input_units={"Fuel_f,bsl,t": "liters or m^3 or kg", "EF_f": "tCO2e/unit fuel"},
        output="E_ff,bsl,t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_ACTIVITY_METHOD",
        applicability="Applicable when machinery, irrigation pumps, or vehicles combust fossil fuel in baseline ALM operations.",
        production_function="calculate_fossil_fuel_emissions",
        test_vector_ref="VECTOR_FF_01",
        notes="Emission factors sourced from IPCC 2006 / National GHG Inventories.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_FOSSIL_FUEL_WP",
        name="Project Emissions from Fossil Fuel Combustion",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.3.1",
        equation_formula="E_ff,wp,t = sum_f (Fuel_f,wp,t * EF_f)",
        inputs=["Fuel_f,wp,t", "EF_f"],
        input_units={"Fuel_f,wp,t": "liters or m^3 or kg", "EF_f": "tCO2e/unit fuel"},
        output="E_ff,wp,t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_ACTIVITY_METHOD",
        applicability="Applicable when machinery, irrigation pumps, or vehicles combust fossil fuel in project ALM operations.",
        production_function="calculate_fossil_fuel_emissions",
        test_vector_ref="VECTOR_FF_01",
        notes="Delta reduction: Delta_CO2_ff,t = E_ff,bsl,t - E_ff,wp,t.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_LIMING_BSL",
        name="Baseline Emissions from Liming",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.2.2",
        equation_formula="E_lime,bsl,t = M_calcitic,bsl,t * 0.4400 + M_dolomite,bsl,t * 0.4767",
        inputs=["M_calcitic,bsl,t", "M_dolomite,bsl,t"],
        input_units={"M_calcitic,bsl,t": "metric tonnes", "M_dolomite,bsl,t": "metric tonnes"},
        output="E_lime,bsl,t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_ACTIVITY_METHOD",
        applicability="Applicable when lime (calcitic limestone or dolomite) is applied to neutralize soil acidity in baseline.",
        production_function="calculate_liming_emissions",
        test_vector_ref="VECTOR_LIME_01",
        notes="IPCC 2006 Vol 4 Ch 11 stoichiometry: 0.12 * (44/12) = 0.4400 for calcitic, 0.13 * (44/12) = 0.4767 for dolomite.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_LIMING_WP",
        name="Project Emissions from Liming",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.3.2",
        equation_formula="E_lime,wp,t = M_calcitic,wp,t * 0.4400 + M_dolomite,wp,t * 0.4767",
        inputs=["M_calcitic,wp,t", "M_dolomite,wp,t"],
        input_units={"M_calcitic,wp,t": "metric tonnes", "M_dolomite,wp,t": "metric tonnes"},
        output="E_lime,wp,t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_ACTIVITY_METHOD",
        applicability="Applicable when lime is applied in project scenario.",
        production_function="calculate_liming_emissions",
        test_vector_ref="VECTOR_LIME_01",
        notes="Delta reduction: Delta_CO2_lime,t = E_lime,bsl,t - E_lime,wp,t.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_N2O_FERT_BSL",
        name="Baseline N2O Emissions from Synthetic and Organic N Fertilizer",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.2.3",
        equation_formula="E_fert,bsl,t = (N_direct * EF1 + N_volat * EF4 + N_leach * EF5) * (44/28) * GWP_N2O",
        inputs=["N_inputs,bsl,t", "EF1", "FracGASF", "FracLEACH", "EF4", "EF5", "GWP_N2O"],
        input_units={"N_inputs,bsl,t": "kg N/yr", "EF1": "kg N2O-N / kg N", "GWP_N2O": "dimensionless"},
        output="E_fert,bsl,t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_DEFAULT_FACTORS",
        applicability="Applicable when synthetic or organic N fertilizer is applied to soils in baseline.",
        production_function="calculate_fertilizer_n2o_emissions",
        test_vector_ref="VECTOR_FERT_01",
        notes="IPCC Tier 1: EF1 = 0.010, FracGASF = 0.10, EF4 = 0.010, FracLEACH = 0.30, EF5 = 0.0075. GWP_N2O = 265 (AR5) or 273 (AR6).",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_N2O_FERT_WP",
        name="Project N2O Emissions from Synthetic and Organic N Fertilizer",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.3.3",
        equation_formula="E_fert,wp,t = (N_direct * EF1 + N_volat * EF4 + N_leach * EF5) * (44/28) * GWP_N2O",
        inputs=["N_inputs,wp,t", "EF1", "FracGASF", "FracLEACH", "EF4", "EF5", "GWP_N2O"],
        input_units={"N_inputs,wp,t": "kg N/yr", "EF1": "kg N2O-N / kg N", "GWP_N2O": "dimensionless"},
        output="E_fert,wp,t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_DEFAULT_FACTORS",
        applicability="Applicable when synthetic or organic N fertilizer is applied in project scenario.",
        production_function="calculate_fertilizer_n2o_emissions",
        test_vector_ref="VECTOR_FERT_01",
        notes="Delta reduction: Delta_N2O_soil,fert,t = E_fert,bsl,t - E_fert,wp,t.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_NFIX_SPECIES",
        name="N2O Emissions from Nitrogen-Fixing Species",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.2.4 / 8.3.4",
        equation_formula="E_nfix,t = N_fixed,t * EF1 * (44/28) * GWP_N2O",
        inputs=["N_fixed,t", "EF1", "GWP_N2O"],
        input_units={"N_fixed,t": "kg N/yr", "EF1": "kg N2O-N / kg N"},
        output="E_nfix,t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_DEFAULT_FACTORS",
        applicability="Applicable when leguminous or N-fixing cover crops or forage species are cultivated.",
        production_function="calculate_nfixing_emissions",
        test_vector_ref="VECTOR_NFIX_01",
        notes="Evaluated separately for baseline and project scenario.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_MANURE_DEPOSITION_CH4",
        name="CH4 Emissions from Manure Deposition by Grazing Livestock",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.2.5 / 8.3.5",
        equation_formula="E_md,CH4,t = Head_t * EF_md_CH4 * 10^-3 * GWP_CH4",
        inputs=["Head_t", "EF_md_CH4", "GWP_CH4"],
        input_units={"Head_t": "head", "EF_md_CH4": "kg CH4/head/yr", "GWP_CH4": "dimensionless"},
        output="E_md,CH4,t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_IPCC_TIER1",
        applicability="Applicable when livestock deposit manure on project land units.",
        production_function="calculate_manure_ch4_emissions",
        test_vector_ref="VECTOR_MANURE_01",
        notes="Separate CH4 component; distinct from N2O manure deposition.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_MANURE_DEPOSITION_N2O",
        name="N2O Emissions from Manure Deposition by Grazing Livestock",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.2.5 / 8.3.5",
        equation_formula="E_md,N2O,t = Head_t * Nex * EF_PRP * (44/28) * 10^-3 * GWP_N2O",
        inputs=["Head_t", "Nex", "EF_PRP", "GWP_N2O"],
        input_units={"Head_t": "head", "Nex": "kg N/head/yr", "EF_PRP": "kg N2O-N / kg N", "GWP_N2O": "dimensionless"},
        output="E_md,N2O,t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_IPCC_TIER1",
        applicability="Applicable when livestock deposit manure on pasture/paddock/rangeland.",
        production_function="calculate_manure_n2o_emissions",
        test_vector_ref="VECTOR_MANURE_01",
        notes="Separate N2O component; distinct from CH4 manure deposition.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_ENTERIC_FERMENTATION",
        name="CH4 Emissions from Livestock Enteric Fermentation",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.2.6 / 8.3.6",
        equation_formula="E_ent,CH4,t = Head_t * EF_ent * 10^-3 * GWP_CH4",
        inputs=["Head_t", "EF_ent", "GWP_CH4"],
        input_units={"Head_t": "head", "EF_ent": "kg CH4/head/yr", "GWP_CH4": "dimensionless"},
        output="E_ent,CH4,t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_IPCC_TIER1_OR_TIER2",
        applicability="Applicable when ruminant or pseudo-ruminant livestock are present on project land units.",
        production_function="calculate_enteric_ch4_emissions",
        test_vector_ref="VECTOR_ENTERIC_01",
        notes="If no livestock present and verified, status is NOT_APPLICABLE.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_BIOMASS_BURNING_CH4",
        name="CH4 Emissions from Biomass Burning",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.2.7 / 8.3.7",
        equation_formula="E_bb,CH4,t = M_burn,t * C_f * G_ef_CH4 * 10^-3 * GWP_CH4",
        inputs=["M_burn,t", "C_f", "G_ef_CH4", "GWP_CH4"],
        input_units={"M_burn,t": "metric tonnes dry matter", "C_f": "fraction", "G_ef_CH4": "g/kg dry matter"},
        output="E_bb,CH4,t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_IPCC_TIER1",
        applicability="Applicable when prescribed fire or crop residue burning occurs.",
        production_function="calculate_biomass_burning_ch4_emissions",
        test_vector_ref="VECTOR_BURN_01",
        notes="Separated from N2O biomass burning.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_BIOMASS_BURNING_N2O",
        name="N2O Emissions from Biomass Burning",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.2.7 / 8.3.7",
        equation_formula="E_bb,N2O,t = M_burn,t * C_f * G_ef_N2O * 10^-3 * GWP_N2O",
        inputs=["M_burn,t", "C_f", "G_ef_N2O", "GWP_N2O"],
        input_units={"M_burn,t": "metric tonnes dry matter", "C_f": "fraction", "G_ef_N2O": "g/kg dry matter"},
        output="E_bb,N2O,t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_IPCC_TIER1",
        applicability="Applicable when prescribed fire or crop residue burning occurs.",
        production_function="calculate_biomass_burning_n2o_emissions",
        test_vector_ref="VECTOR_BURN_01",
        notes="Separated from CH4 biomass burning.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_SOIL_METHANOGENESIS",
        name="Soil Methanogenesis CH4 Emissions",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.2.8 / 8.3.8",
        equation_formula="E_methanogenesis = Model_Simulated_CH4(QA1)",
        inputs=["soil_water_regime", "organic_amendments", "biogeochemical_parameters"],
        input_units={"Model_Simulated_CH4": "tCO2e/yr"},
        output="E_methanogenesis",
        output_units="tCO2e/yr",
        quantification_approach="QA1_MODEL_ONLY",
        applicability="Applicable in flooded rice systems or saturated soils. QA2 is NOT permitted by Table 5.",
        production_function="evaluate_soil_methanogenesis_status",
        test_vector_ref="VECTOR_METH_01",
        notes="Fail-closed policy: if applicable and no approved VMD0053 model is configured, blocks calculation.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_44",
        name="Baseline Scenario Total Carbon Stock Change",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.5.1",
        equation_formula="Delta_CO2_bsl,t = Delta_CO2_soil_bsl,t * (1 - UNC_t,CO2 * I(Delta_CO2_soil_t)) + Delta_C_TREE,bsl,t + Delta_C_SHRUB,bsl,t",
        inputs=["Delta_CO2_soil_bsl,t", "UNC_t,CO2", "I(Delta_CO2_soil_t)", "Delta_C_TREE,bsl,t", "Delta_C_SHRUB,bsl,t"],
        input_units={"all": "tCO2e/yr"},
        output="Delta_CO2_bsl,t",
        output_units="tCO2e/yr",
        quantification_approach="QA2_FOR_SOC_PLUS_QA3_FOR_WOODY",
        applicability="Mandatory total carbon stock change across all applicable carbon pools in baseline.",
        production_function="calculate_total_stock_change_bsl",
        test_vector_ref="VECTOR_EQ44_01",
        notes="Becomes CALCULATED when SOC and all applicable woody pools (tree, shrub) are resolved.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_45",
        name="Project Scenario Total Carbon Stock Change",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.5.1",
        equation_formula="Delta_CO2_wp,t = Delta_CO2_soil_wp,t * (1 - UNC_t,CO2 * I(Delta_CO2_soil_t)) + Delta_C_TREE,wp,t + Delta_C_SHRUB,wp,t",
        inputs=["Delta_CO2_soil_wp,t", "UNC_t,CO2", "I(Delta_CO2_soil_t)", "Delta_C_TREE,wp,t", "Delta_C_SHRUB,wp,t"],
        input_units={"all": "tCO2e/yr"},
        output="Delta_CO2_wp,t",
        output_units="tCO2e/yr",
        quantification_approach="QA2_FOR_SOC_PLUS_QA3_FOR_WOODY",
        applicability="Mandatory total carbon stock change across all applicable carbon pools in project scenario.",
        production_function="calculate_total_stock_change_wp",
        test_vector_ref="VECTOR_EQ45_01",
        notes="Becomes CALCULATED when SOC and all applicable woody pools (tree, shrub) are resolved.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_LEAKAGE_TOTAL",
        name="Total Leakage Across Verification Period",
        official_source="VM0042 + 11 June 2026 C&C",
        version="2.2 (21 Oct 2025) + C&C 11 June 2026",
        section="Section 8.4",
        equation_formula="TOTAL_LEAKAGE_t = LEOA,t + LKdisp,t + LEBR,t",
        inputs=["LEOA,t", "LKdisp,t", "LEBR,t"],
        input_units={"all": "tCO2e/yr"},
        output="TOTAL_LEAKAGE_t",
        output_units="tCO2e/yr",
        quantification_approach="QA3_ACTIVITY_AND_MARKET_LEAKAGE",
        applicability="Mandatory evaluation of all 3 leakage pathways (LEOA ecological, LKdisp production decline via VMD0054 v1.1 Eq 13 / v1.0 Eq 10, LEBR residue via TOOL16).",
        production_function="calculate_total_leakage",
        test_vector_ref="VECTOR_LK_01",
        notes="Production decline uses 11 June 2026 C&C modifications to VMD0054 (v1.1 Eq 13 or v1.0 Eq 10 via VM0042 Eq 36). Residue uses TOOL16.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_36",
        name="Production Decline Leakage Allocation (11 June 2026 C&C)",
        official_source="VM0042 + 11 June 2026 C&C",
        version="2.2 (21 Oct 2025) + C&C 11 June 2026",
        section="Section 8.4 Eq. 36",
        equation_formula="LKdisp,t = max(0, LK_t - LK_prior) / years",
        inputs=["LK_t", "LK_prior", "years"],
        input_units={"LK_t": "tCO2e", "LK_prior": "tCO2e", "years": "yr"},
        output="LKdisp,t",
        output_units="tCO2e/yr",
        quantification_approach="MARKET_LEAKAGE_ALLOCATION",
        applicability="Allocates cumulative market leakage from VMD0054 over verification period.",
        production_function="calculate_vm0042_equation_36_market_leakage",
        test_vector_ref="VECTOR_EQ36_01",
        notes="Consumes cumulative LK_t from VMD0054 v1.1 Eq. 13 (or v1.0 Eq. 10). Preserves units.",
    ),
    EquationDefinition(
        equation_id="VMD0054_V1.1_EQ11",
        name="Carbon Stock Change on Converted Land (Delta CS)",
        official_source="VMD0054",
        version="1.1",
        section="Equation 11",
        equation_formula="Delta_CS = Delta_C_biomass + Delta_SOC",
        inputs=["Delta_C_biomass", "Delta_SOC"],
        input_units={"Delta_C_biomass": "t C/ha", "Delta_SOC": "t C/ha"},
        output="Delta_CS",
        output_units="t C/ha",
        quantification_approach="CARBON_STOCK_INTENSITY",
        applicability="Calculates carbon stock difference per hectare on newly converted land. Output is in t C/ha, NOT cumulative leakage tCO2e.",
        production_function="calculate_vmd0054_v11_equation_11_delta_cs",
        test_vector_ref="VECTOR_VMD0054_EQ11",
        notes="Supplies Delta_CS into VMD0054 v1.1 Eq. 13.",
    ),
    EquationDefinition(
        equation_id="VMD0054_V1.1_EQ13",
        name="Cumulative Market Leakage from Production Decline",
        official_source="VMD0054",
        version="1.1",
        section="Equation 13",
        equation_formula="LK_t = AL_t * Delta_CS * (44/12) + ELM_t",
        inputs=["AL_t", "Delta_CS", "ELM_t"],
        input_units={"AL_t": "ha", "Delta_CS": "t C/ha", "ELM_t": "tCO2e"},
        output="LK_t",
        output_units="tCO2e",
        quantification_approach="CUMULATIVE_MARKET_LEAKAGE",
        applicability="Active standard module equation calculating cumulative market leakage in tCO2e. Supplies LK_t into VM0042 Eq. 36.",
        production_function="calculate_vmd0054_v11_equation_13_cumulative_leakage",
        test_vector_ref="VECTOR_VMD0054_EQ13",
        notes="Active standard pathway for all projects unless verified pre-2027 transition eligible.",
    ),
    EquationDefinition(
        equation_id="VMD0054_V1.0_EQ10",
        name="Cumulative Market Leakage from Production Decline (v1.0 Transition)",
        official_source="VMD0054",
        version="1.0",
        section="Equation 10",
        equation_formula="LK_t = AL_t * Delta_CS * (44/12) + ELM_t",
        inputs=["AL_t", "Delta_CS", "ELM_t"],
        input_units={"AL_t": "ha", "Delta_CS": "t C/ha", "ELM_t": "tCO2e"},
        output="LK_t",
        output_units="tCO2e",
        quantification_approach="CUMULATIVE_MARKET_LEAKAGE_TRANSITION",
        applicability="Transition route for projects meeting Verra pre-2027 transition criteria. Supplies LK_t into VM0042 Eq. 36.",
        production_function="calculate_vmd0054_v10_equation_10_cumulative_leakage",
        test_vector_ref="VECTOR_VMD0054_V10_EQ10",
        notes="Operative strictly when Verra submission deadline (31 Jan 2027) and request type are verified.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_37",
        name="Gross GHG Emission Reductions (Before Leakage)",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.5",
        equation_formula="ER_t = I(Delta_CO2_wp) * (sum(Delta_E_sources,t) + min(0, Delta_CO2_wp,t) - min(0, Delta_CO2_bsl,t)) + (1 - I(Delta_CO2_wp)) * (sum(Delta_E_sources,t) + min(0, Delta_CO2_wp,t) - min(0, Delta_CO2_bsl,t) + max(0, Delta_CO2_wp,t) - max(0, Delta_CO2_bsl,t))",
        inputs=["Delta_E_sources,t", "Delta_CO2_wp,t", "Delta_CO2_bsl,t", "I(Delta_CO2_wp)"],
        input_units={"all": "tCO2e/yr"},
        output="ER_t",
        output_units="tCO2e/yr",
        quantification_approach="INTEGRATED_ACCOUNTING",
        applicability="Computes gross emission reductions using official literal stock-change branches without outer zero-clamping.",
        production_function="calculate_equation_37_gross_reductions",
        test_vector_ref="VECTOR_EQ37_01",
        notes="Official VM0042 v2.2 literal dual-branch form without outer zero clamp. When I=1: sum(Delta_E_sources,t) + min(0, Delta_CO2_wp,t) - min(0, Delta_CO2_bsl,t). When I=0: sum(Delta_E_sources,t) + (min - min) + (max - max). Negative results are preserved to protect against silently discarding adverse annual performance.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_38",
        name="Net GHG Emission Reductions",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.5",
        equation_formula="ERNET_t = ER_t - LKER_t",
        inputs=["ER_t", "LKER_t"],
        input_units={"all": "tCO2e/yr"},
        output="ERNET_t",
        output_units="tCO2e/yr",
        quantification_approach="INTEGRATED_ACCOUNTING",
        applicability="Deducts allocated leakage from gross reductions.",
        production_function="calculate_equation_38_net_reductions",
        test_vector_ref="VECTOR_EQ38_01",
        notes="Reconciles with Eq. 37 and Eq. 39.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_39",
        name="Leakage Allocation to Reductions",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.5",
        equation_formula="LKER_t = LK_t * (ER_t / (ER_t + CR_t)) if (ER_t + CR_t) > 0 else 0",
        inputs=["LK_t", "ER_t", "CR_t"],
        input_units={"all": "tCO2e/yr"},
        output="LKER_t",
        output_units="tCO2e/yr",
        quantification_approach="PROPORTIONAL_ALLOCATION",
        applicability="Proportionally allocates total leakage to reductions.",
        production_function="calculate_equation_39_leakage_allocation_er",
        test_vector_ref="VECTOR_EQ39_01",
        notes="Fails closed / safe deterministic zero when ER_t + CR_t == 0.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_40",
        name="Carbon Dioxide Removals (Before Leakage)",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.5",
        equation_formula="CR_t = I(Delta_CO2_wp) * max(0, Delta_CO2_wp,t - max(0, Delta_CO2_bsl,t))",
        inputs=["Delta_CO2_wp,t", "Delta_CO2_bsl,t", "I(Delta_CO2_wp)"],
        input_units={"all": "tCO2e/yr"},
        output="CR_t",
        output_units="tCO2e/yr",
        quantification_approach="INTEGRATED_ACCOUNTING",
        applicability="Computes gross carbon dioxide removals. Operative only when cumulative project carbon stock is positive.",
        production_function="calculate_equation_40_gross_removals",
        test_vector_ref="VECTOR_EQ40_01",
        notes="If cumulative project carbon stock change <= 0, CR_t = 0.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_41",
        name="Net Carbon Dioxide Removals",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.5",
        equation_formula="CRNET_t = CR_t - LKCR_t",
        inputs=["CR_t", "LKCR_t"],
        input_units={"all": "tCO2e/yr"},
        output="CRNET_t",
        output_units="tCO2e/yr",
        quantification_approach="INTEGRATED_ACCOUNTING",
        applicability="Deducts allocated leakage from gross removals.",
        production_function="calculate_equation_41_net_removals",
        test_vector_ref="VECTOR_EQ41_01",
        notes="Reconciles with Eq. 40 and Eq. 42.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_42",
        name="Leakage Allocation to Removals",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.5",
        equation_formula="LKCR_t = LK_t * (CR_t / (ER_t + CR_t)) if (ER_t + CR_t) > 0 else 0",
        inputs=["LK_t", "ER_t", "CR_t"],
        input_units={"all": "tCO2e/yr"},
        output="LKCR_t",
        output_units="tCO2e/yr",
        quantification_approach="PROPORTIONAL_ALLOCATION",
        applicability="Proportionally allocates total leakage to removals.",
        production_function="calculate_equation_42_leakage_allocation_cr",
        test_vector_ref="VECTOR_EQ42_01",
        notes="Reconciliation guarantee: LKER_t + LKCR_t == LK_t.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_43",
        name="Total Net GHG Reductions and Removals",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.5",
        equation_formula="ERRNET_t = ERNET_t + CRNET_t",
        inputs=["ERNET_t", "CRNET_t"],
        input_units={"all": "tCO2e/yr"},
        output="ERRNET_t",
        output_units="tCO2e/yr",
        quantification_approach="INTEGRATED_ACCOUNTING",
        applicability="Overall net climate benefit from project activities.",
        production_function="calculate_equation_43_total_net",
        test_vector_ref="VECTOR_EQ43_01",
        notes="Named PROJECT_NET_GHG_REDUCTIONS_REMOVALS. Distinct from VCU issuance.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_75",
        name="Non-Permanence Risk Buffer Deduction for Reductions",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.7",
        equation_formula="BuER,t = NPR * [I(Delta_CO2_wp) * (min(0, Delta_CO2_wp,t) - min(0, Delta_CO2_bsl,t)) + (1 - I(Delta_CO2_wp)) * (min(0, Delta_CO2_wp,t) - min(0, Delta_CO2_bsl,t) + max(0, Delta_CO2_wp,t) - max(0, Delta_CO2_bsl,t))]",
        inputs=["NPR", "Delta_CO2_wp,t", "Delta_CO2_bsl,t", "I(Delta_CO2_wp)"],
        input_units={"NPR": "fraction", "Delta_CO2_wp,t": "tCO2e/yr", "Delta_CO2_bsl,t": "tCO2e/yr"},
        output="BuER,t",
        output_units="tCO2e/yr",
        quantification_approach="VCS_AFOLU_BUFFER_CALCULATION",
        applicability="Computes non-permanence buffer deduction for stock-change emission reductions without outer zero-clamping.",
        production_function="calculate_equation_75_buffer_reductions",
        test_vector_ref="VECTOR_EQ75_01",
        notes="Exact VM0042 Section 8.7 Eq. 75 without outer zero clamp.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_76",
        name="Non-Permanence Risk Buffer Deduction for Removals",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.7",
        equation_formula="BuCR,t = I(Delta_CO2_wp) * [max(0, Delta_CO2_wp,t) - max(0, Delta_CO2_bsl,t)] * NPR = CR_t * NPR",
        inputs=["NPR", "CR_t", "I(Delta_CO2_wp)"],
        input_units={"NPR": "fraction", "CR_t": "tCO2e/yr"},
        output="BuCR,t",
        output_units="tCO2e/yr",
        quantification_approach="VCS_AFOLU_BUFFER_CALCULATION",
        applicability="Applies to qualifying carbon-stock-change gross removals before leakage. NOT CRNET * NPR%.",
        production_function="calculate_equation_76_buffer_removals",
        test_vector_ref="VECTOR_EQ76_01",
        notes="Bu_t = BuER,t + BuCR,t.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_77",
        name="Reduction-Side Internal VCU Eligible Quantity",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.7",
        equation_formula="VCU_ER,t = ERNET_t - BUF_ER,t",
        inputs=["ERNET_t", "BUF_ER,t"],
        input_units={"all": "tCO2e/yr"},
        output="VCU_ER,t",
        output_units="tCO2e/yr",
        quantification_approach="VCS_VCU_ELIGIBILITY",
        applicability="Computes internal reduction-side VCU-eligible volume.",
        production_function="calculate_equation_77_vcu_reductions",
        test_vector_ref="VECTOR_EQ77_01",
        notes="Labeled INTERNAL_VCU_ELIGIBLE_QUANTITY_REDUCTIONS.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_78",
        name="Removal-Side Internal VCU Eligible Quantity",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.7",
        equation_formula="VCU_CR,t = CRNET_t - BUF_CR,t",
        inputs=["CRNET_t", "BUF_CR,t"],
        input_units={"all": "tCO2e/yr"},
        output="VCU_CR,t",
        output_units="tCO2e/yr",
        quantification_approach="VCS_VCU_ELIGIBILITY",
        applicability="Computes internal removal-side VCU-eligible volume.",
        production_function="calculate_equation_78_vcu_removals",
        test_vector_ref="VECTOR_EQ78_01",
        notes="Labeled INTERNAL_VCU_ELIGIBLE_QUANTITY_REMOVALS.",
    ),
    EquationDefinition(
        equation_id="VM0042_EQ_79",
        name="Total Internal VCU Eligible Quantity",
        official_source="VM0042",
        version="2.2 (21 Oct 2025)",
        section="Section 8.7",
        equation_formula="VCU_t = VCU_ER,t + VCU_CR,t = ERRNET_t - (BUF_ER,t + BUF_CR,t)",
        inputs=["VCU_ER,t", "VCU_CR,t"],
        input_units={"all": "tCO2e/yr"},
        output="VCU_t",
        output_units="tCO2e/yr",
        quantification_approach="VCS_VCU_ELIGIBILITY",
        applicability="Overall internal calculated eligible volume. Requires authoritative NPR assessment.",
        production_function="calculate_equation_79_total_vcu",
        test_vector_ref="VECTOR_EQ79_01",
        notes="STRICTLY LABELED: INTERNAL_VCU_ELIGIBLE_QUANTITY. Never 'ISSUED VCUs'.",
    ),
]


def get_equation_matrix_dict() -> List[Dict[str, Any]]:
    return [eq.to_dict() for eq in VM0042_EQUATION_MATRIX]
