"""restore_carbon_calculation_model

Revision ID: a66002ee17ef
Revises: 3307d715f0e7
Create Date: 2026-07-13 21:05:15.951275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a66002ee17ef'
down_revision = '3307d715f0e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_c_sink_transactions_c_sink_unit_id', table_name='c_sink_transactions')
    op.drop_table('c_sink_transactions')
    op.drop_table('schema_evolution_logs')
    op.drop_index('ix_c_sink_units_project_id', table_name='c_sink_units')
    op.drop_table('c_sink_units')
    op.drop_index('ix_sensor_readings_asset_id', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index('ix_community_validations_asset_id', table_name='community_validations')
    op.drop_index('ix_community_validations_validator_id', table_name='community_validations')
    op.drop_table('community_validations')
    op.drop_index('ix_kiln_profiles_artisan_id', table_name='kiln_profiles')
    op.drop_table('kiln_profiles')
    op.drop_index('ix_outbox_events_event_type', table_name='outbox_events')
    op.drop_index('ix_outbox_events_published', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_audit_tasks_asset_id', table_name='audit_tasks')
    op.drop_index('ix_audit_tasks_assigned_agent', table_name='audit_tasks')
    op.drop_table('audit_tasks')
    op.drop_index('ix_community_comments_user_id', table_name='community_comments')
    op.drop_index('ix_community_comments_validation_id', table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_index('ix_data_asset_catalogue_asset_name', table_name='data_asset_catalogue')
    op.drop_table('data_asset_catalogue')
    op.drop_index('ix_biochar_batches_batch_id', table_name='biochar_batches')
    op.drop_index('ix_biochar_batches_biomass_id', table_name='biochar_batches')
    op.drop_index('ix_biochar_batches_kiln_id', table_name='biochar_batches')
    op.drop_table('biochar_batches')
    op.drop_index('ix_access_requests_email', table_name='access_requests')
    op.drop_table('access_requests')
    op.drop_index('ix_saga_states_saga_type', table_name='saga_states')
    op.drop_table('saga_states')
    op.drop_table('artisan_profiles')
    op.drop_table('biomass_profiles')
    op.drop_index('ix_qr_records_batch_id', table_name='qr_records')
    op.drop_index('ix_qr_records_qr_id', table_name='qr_records')
    op.drop_table('qr_records')
    op.drop_index('ix_job_executions_created_by', table_name='job_executions')
    op.drop_index('ix_job_executions_id', table_name='job_executions')
    op.drop_index('ix_job_executions_job_type', table_name='job_executions')
    op.drop_index('ix_job_executions_status', table_name='job_executions')
    op.drop_index('ix_job_executions_status_created_at', table_name='job_executions')
    op.drop_index('ix_job_executions_target_id', table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_index('ix_anomaly_flags_activity_id', table_name='anomaly_flags')
    op.drop_index('ix_anomaly_flags_flag_type', table_name='anomaly_flags')
    op.drop_index('ix_anomaly_flags_user_id', table_name='anomaly_flags')
    op.drop_table('anomaly_flags')
    op.add_column('carbon_calculations', sa.Column('methodology_version_id', sa.UUID(), nullable=True))
    op.add_column('carbon_calculations', sa.Column('tco2e_yield', sa.Float(), nullable=False))
    op.add_column('carbon_calculations', sa.Column('uncertainty', sa.Float(), nullable=True))
    op.add_column('carbon_calculations', sa.Column('execution_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('carbon_calculations', sa.Column('execution_outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('carbon_calculations', sa.Column('audit_replay', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('carbon_calculations', sa.Column('registry_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('carbon_calculations', sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('carbon_calculations', 'activity_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('fk_carbon_calculations_project_id_projects', 'carbon_calculations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_carbon_calculations_activity_id_activities'), 'carbon_calculations', 'activities', ['activity_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_carbon_calculations_methodology_version_id_methodology_versions'), 'carbon_calculations', 'methodology_versions', ['methodology_version_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_carbon_calculations_project_id_projects'), 'carbon_calculations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('carbon_calculations', 'status')
    op.drop_column('carbon_calculations', 'created_at')
    op.drop_column('carbon_calculations', 'calculation_log')
    op.drop_column('carbon_calculations', 'methodology_used')
    op.drop_column('carbon_calculations', 'tco2e_generated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carbon_calculations', sa.Column('tco2e_generated', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('carbon_calculations', sa.Column('methodology_used', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('carbon_calculations', sa.Column('calculation_log', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('carbon_calculations', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('carbon_calculations', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_carbon_calculations_project_id_projects'), 'carbon_calculations', type_='foreignkey')
    op.drop_constraint(op.f('fk_carbon_calculations_methodology_version_id_methodology_versions'), 'carbon_calculations', type_='foreignkey')
    op.drop_constraint(op.f('fk_carbon_calculations_activity_id_activities'), 'carbon_calculations', type_='foreignkey')
    op.create_foreign_key('fk_carbon_calculations_project_id_projects', 'carbon_calculations', 'projects', ['project_id'], ['id'])
    op.alter_column('carbon_calculations', 'activity_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('carbon_calculations', 'executed_at')
    op.drop_column('carbon_calculations', 'registry_references')
    op.drop_column('carbon_calculations', 'audit_replay')
    op.drop_column('carbon_calculations', 'execution_outputs')
    op.drop_column('carbon_calculations', 'execution_inputs')
    op.drop_column('carbon_calculations', 'uncertainty')
    op.drop_column('carbon_calculations', 'tco2e_yield')
    op.drop_column('carbon_calculations', 'methodology_version_id')
    op.create_table('anomaly_flags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('flag_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('resolved_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_anomaly_flags_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_anomaly_flags')
    )
    op.create_index('ix_anomaly_flags_user_id', 'anomaly_flags', ['user_id'], unique=False)
    op.create_index('ix_anomaly_flags_flag_type', 'anomaly_flags', ['flag_type'], unique=False)
    op.create_index('ix_anomaly_flags_activity_id', 'anomaly_flags', ['activity_id'], unique=False)
    op.create_table('job_executions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('target_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_job_executions')
    )
    op.create_index('ix_job_executions_target_id', 'job_executions', ['target_id'], unique=False)
    op.create_index('ix_job_executions_status_created_at', 'job_executions', ['status', 'created_at'], unique=False)
    op.create_index('ix_job_executions_status', 'job_executions', ['status'], unique=False)
    op.create_index('ix_job_executions_job_type', 'job_executions', ['job_type'], unique=False)
    op.create_index('ix_job_executions_id', 'job_executions', ['id'], unique=False)
    op.create_index('ix_job_executions_created_by', 'job_executions', ['created_by'], unique=False)
    op.create_table('qr_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('qr_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('verification_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['biochar_batches.id'], name='fk_qr_records_batch_id_biochar_batches', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_qr_records')
    )
    op.create_index('ix_qr_records_qr_id', 'qr_records', ['qr_id'], unique=False)
    op.create_index('ix_qr_records_batch_id', 'qr_records', ['batch_id'], unique=False)
    op.create_table('biomass_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mixing_ratio', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('carbon_content_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('bulk_density_g_cm3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('methane_compensation_scheme', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('gps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('evidence_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_biomass_profiles'),
    postgresql_ignore_search_path=False
    )
    op.create_table('artisan_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('kiln_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('proficiency_passed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('volume_measuring_device_m3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('gps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('evidence_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_artisan_profiles'),
    sa.UniqueConstraint('client_id', name='uq_artisan_profiles_client_id'),
    postgresql_ignore_search_path=False
    )
    op.create_table('saga_states',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('saga_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_saga_states')
    )
    op.create_index('ix_saga_states_saga_type', 'saga_states', ['saga_type'], unique=False)
    op.create_table('access_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('organization_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('use_case', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_access_requests')
    )
    op.create_index('ix_access_requests_email', 'access_requests', ['email'], unique=False)
    op.create_table('biochar_batches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('kiln_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('biomass_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('quantity_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('produced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('lab_report_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('batch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('batch_weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('production_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('kiln_capacity_limit_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('gps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('evidence_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['biomass_id'], ['biomass_profiles.id'], name='fk_biochar_batches_biomass_id_biomass_profiles', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kiln_id'], ['kiln_profiles.id'], name='fk_biochar_batches_kiln_id_kiln_profiles', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_biochar_batches'),
    sa.UniqueConstraint('batch_number', name='uq_biochar_batches_batch_number')
    )
    op.create_index('ix_biochar_batches_kiln_id', 'biochar_batches', ['kiln_id'], unique=False)
    op.create_index('ix_biochar_batches_biomass_id', 'biochar_batches', ['biomass_id'], unique=False)
    op.create_index('ix_biochar_batches_batch_id', 'biochar_batches', ['batch_id'], unique=False)
    op.create_table('data_asset_catalogue',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('domain_owner', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contains_pii', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pii_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('gdpr_consent_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('retention_period_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('archive_after_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upstream_sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('downstream_consumers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('current_schema_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('schema_definition', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_data_asset_catalogue'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_data_asset_catalogue_asset_name', 'data_asset_catalogue', ['asset_name'], unique=False)
    op.create_table('community_comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('validation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_community_comments_user_id_users', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_id'], ['community_validations.id'], name='fk_community_comments_validation_id_community_validations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_community_comments')
    )
    op.create_index('ix_community_comments_validation_id', 'community_comments', ['validation_id'], unique=False)
    op.create_index('ix_community_comments_user_id', 'community_comments', ['user_id'], unique=False)
    op.create_table('audit_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_agent', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['properties.id'], name='fk_audit_tasks_asset_id_properties'),
    sa.ForeignKeyConstraint(['assigned_agent'], ['users.id'], name='fk_audit_tasks_assigned_agent_users'),
    sa.PrimaryKeyConstraint('id', name='pk_audit_tasks')
    )
    op.create_index('ix_audit_tasks_assigned_agent', 'audit_tasks', ['assigned_agent'], unique=False)
    op.create_index('ix_audit_tasks_asset_id', 'audit_tasks', ['asset_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stream_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_outbox_events')
    )
    op.create_index('ix_outbox_events_published', 'outbox_events', ['published'], unique=False)
    op.create_index('ix_outbox_events_event_type', 'outbox_events', ['event_type'], unique=False)
    op.create_table('kiln_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('artisan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('surface_area_m2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('depth_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('capacity_m3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('methane_emission_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('gps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('evidence_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan_profiles.id'], name='fk_kiln_profiles_artisan_id_artisan_profiles', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_kiln_profiles'),
    sa.UniqueConstraint('serial_number', name='uq_kiln_profiles_serial_number')
    )
    op.create_index('ix_kiln_profiles_artisan_id', 'kiln_profiles', ['artisan_id'], unique=False)
    op.create_table('community_validations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('validator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('response', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('upvotes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['properties.id'], name='fk_community_validations_asset_id_properties'),
    sa.ForeignKeyConstraint(['validator_id'], ['users.id'], name='fk_community_validations_validator_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_community_validations')
    )
    op.create_index('ix_community_validations_validator_id', 'community_validations', ['validator_id'], unique=False)
    op.create_index('ix_community_validations_asset_id', 'community_validations', ['asset_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('usage_flag', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fuel_weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('battery_voltage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['properties.id'], name='fk_sensor_readings_asset_id_properties'),
    sa.PrimaryKeyConstraint('id', name='pk_sensor_readings')
    )
    op.create_index('ix_sensor_readings_asset_id', 'sensor_readings', ['asset_id'], unique=False)
    op.create_table('c_sink_units',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('total_co2e_t', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('carbon_content_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('biomass_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('pyrolysis_technology', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('matrix_category', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('gps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('evidence_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_c_sink_units_project_id_projects', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_c_sink_units'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_c_sink_units_project_id', 'c_sink_units', ['project_id'], unique=False)
    op.create_table('schema_evolution_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('migration_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['data_asset_catalogue.id'], name='fk_schema_evolution_logs_asset_id_data_asset_catalogue'),
    sa.PrimaryKeyConstraint('id', name='pk_schema_evolution_logs')
    )
    op.create_table('c_sink_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('c_sink_unit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('registry_tx_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('response_log', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['c_sink_unit_id'], ['c_sink_units.id'], name='fk_c_sink_transactions_c_sink_unit_id_c_sink_units', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_c_sink_transactions')
    )
    op.create_index('ix_c_sink_transactions_c_sink_unit_id', 'c_sink_transactions', ['c_sink_unit_id'], unique=False)
    # ### end Alembic commands ###
