"""Add missing tables

Revision ID: 3307d715f0e7
Revises: a0c384e3a864
Create Date: 2026-07-13 09:37:53.362259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3307d715f0e7'
down_revision = 'a0c384e3a864'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
