"""Sync DB state

Revision ID: 93cd14d5bc1f
Revises: 5a371e075f07
Create Date: 2026-05-02 20:58:15.744261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93cd14d5bc1f'
down_revision = '5a371e075f07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_readings', 'usage_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_readings', 'usage_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
