"""add_ndvi_records_table

Revision ID: cbfd9fa390e7
Revises: 93cd14d5bc1f
Create Date: 2026-05-08 09:29:58.203587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbfd9fa390e7'
down_revision = '93cd14d5bc1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('methodology_id', sa.String(), nullable=False),
    sa.Column('registry_id', sa.String(), nullable=True),
    sa.Column('baseline_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_methodology_id'), 'projects', ['methodology_id'], unique=False)
    op.create_table('ndvi_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('ndvi_score', sa.Float(), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=False),
    sa.Column('observation_date', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['properties.id'], name=op.f('fk_ndvi_records_asset_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ndvi_records'))
    )
    op.create_index(op.f('ix_ndvi_records_asset_id'), 'ndvi_records', ['asset_id'], unique=False)
    op.create_table('carbon_calculations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('methodology_used', sa.String(), nullable=False),
    sa.Column('tco2e_generated', sa.Float(), nullable=False),
    sa.Column('calculation_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_carbon_calculations_activity_id_activities')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_carbon_calculations_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carbon_calculations'))
    )
    op.create_index(op.f('ix_carbon_calculations_activity_id'), 'carbon_calculations', ['activity_id'], unique=False)
    op.create_index(op.f('ix_carbon_calculations_project_id'), 'carbon_calculations', ['project_id'], unique=False)
    op.add_column('sensor_readings', sa.Column('fuel_weight_kg', sa.Float(), nullable=True))
    op.add_column('sensor_readings', sa.Column('battery_voltage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'battery_voltage')
    op.drop_column('sensor_readings', 'fuel_weight_kg')
    op.drop_index(op.f('ix_carbon_calculations_project_id'), table_name='carbon_calculations')
    op.drop_index(op.f('ix_carbon_calculations_activity_id'), table_name='carbon_calculations')
    op.drop_table('carbon_calculations')
    op.drop_index(op.f('ix_ndvi_records_asset_id'), table_name='ndvi_records')
    op.drop_table('ndvi_records')
    op.drop_index(op.f('ix_projects_methodology_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
