"""Initial CIOS Architecture Schema

Revision ID: a0c384e3a864
Revises: 
Create Date: 2026-07-13 02:16:11.025295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0c384e3a864'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('vvb_org_id', sa.UUID(), nullable=False),
    sa.Column('report_uri', sa.String(length=500), nullable=False),
    sa.Column('report_hash', sa.String(length=64), nullable=False),
    sa.Column('is_positive_opinion', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_reports'))
    )
    op.create_table('audit_trails',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_trails'))
    )
    op.create_table('compliance_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('eligibility_status', sa.String(length=20), nullable=False),
    sa.Column('sampling_status', sa.String(length=20), nullable=False),
    sa.Column('conformance_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('last_evaluated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_runs'))
    )
    op.create_index(op.f('ix_compliance_runs_project_id'), 'compliance_runs', ['project_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=True)
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=True)
    op.create_table('emission_factor_registry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('fuel_type', sa.String(length=100), nullable=True),
    sa.Column('grid_type', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_factor_registry'))
    )
    op.create_index(op.f('ix_emission_factor_registry_code'), 'emission_factor_registry', ['code'], unique=True)
    op.create_index(op.f('ix_emission_factor_registry_country'), 'emission_factor_registry', ['country'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('from_org_id', sa.UUID(), nullable=False),
    sa.Column('to_org_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_transactions'))
    )
    op.create_table('jurisdictions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('metadata_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spatial_boundary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['jurisdictions.id'], name=op.f('fk_jurisdictions_parent_id_jurisdictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jurisdictions'))
    )
    op.create_index(op.f('ix_jurisdictions_code'), 'jurisdictions', ['code'], unique=True)
    op.create_table('marketplace_listings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_listings'))
    )
    op.create_table('methodology_calculation_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('formula', sa.String(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('inputs_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sensitivity_analysis_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_calculation_rules'))
    )
    op.create_index(op.f('ix_methodology_calculation_rules_code'), 'methodology_calculation_rules', ['code'], unique=True)
    op.create_table('methodology_evidence_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_evidence_templates'))
    )
    op.create_index(op.f('ix_methodology_evidence_templates_code'), 'methodology_evidence_templates', ['code'], unique=True)
    op.create_table('methodology_families',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_families'))
    )
    op.create_index(op.f('ix_methodology_families_code'), 'methodology_families', ['code'], unique=True)
    op.create_table('methodology_monitoring_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('validation_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_monitoring_templates'))
    )
    op.create_index(op.f('ix_methodology_monitoring_templates_code'), 'methodology_monitoring_templates', ['code'], unique=True)
    op.create_table('methodology_packages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('schema_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculator_formulas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_packages'))
    )
    op.create_table('methodology_registries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_registries'))
    )
    op.create_index(op.f('ix_methodology_registries_code'), 'methodology_registries', ['code'], unique=True)
    op.create_table('methodology_reporting_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('template_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_reporting_templates'))
    )
    op.create_index(op.f('ix_methodology_reporting_templates_code'), 'methodology_reporting_templates', ['code'], unique=True)
    op.create_table('methodology_validation_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('expression', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_validation_rules'))
    )
    op.create_index(op.f('ix_methodology_validation_rules_code'), 'methodology_validation_rules', ['code'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('metadata_context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('max_installations', sa.Integer(), nullable=False),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('api_calls_count', sa.Integer(), nullable=False),
    sa.Column('licensed_methodologies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('protocol_definitions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('parser_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transformation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protocol_definitions')),
    sa.UniqueConstraint('name', name=op.f('uq_protocol_definitions_name'))
    )
    op.create_table('registry_adapters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('adapter_type', sa.String(length=100), nullable=False),
    sa.Column('endpoint_url', sa.String(length=1024), nullable=True),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registry_adapters'))
    )
    op.create_table('registry_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('adapter_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapping_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registry_configs')),
    sa.UniqueConstraint('name', name=op.f('uq_registry_configs_name'))
    )
    op.create_table('sensor_metadata',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sensor_type', sa.String(length=50), nullable=False),
    sa.Column('unit_of_measurement', sa.String(length=20), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_metadata')),
    sa.UniqueConstraint('sensor_type', name=op.f('uq_sensor_metadata_sensor_type'))
    )
    op.create_table('signatures',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('signer_id', sa.UUID(), nullable=True),
    sa.Column('signer_role', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('signature_hash', sa.String(length=512), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signatures'))
    )
    op.create_table('trust_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('gps_score', sa.Float(), nullable=False),
    sa.Column('image_score', sa.Float(), nullable=False),
    sa.Column('frequency_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trust_logs'))
    )
    op.create_index(op.f('ix_trust_logs_activity_id'), 'trust_logs', ['activity_id'], unique=False)
    op.create_table('validation_bodies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('accreditation_number', sa.String(length=100), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_bodies')),
    sa.UniqueConstraint('accreditation_number', name=op.f('uq_validation_bodies_accreditation_number'))
    )
    op.create_table('verification_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('verifier_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_tasks'))
    )
    op.create_table('climate_programmes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('funding_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], name=op.f('fk_climate_programmes_jurisdiction_id_jurisdictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_climate_programmes'))
    )
    op.create_table('compliance_frameworks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reporting_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], name=op.f('fk_compliance_frameworks_jurisdiction_id_jurisdictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_frameworks'))
    )
    op.create_table('emission_factor_libraries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], name=op.f('fk_emission_factor_libraries_jurisdiction_id_jurisdictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_factor_libraries'))
    )
    op.create_table('governance_authorities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('authority_type', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('metadata_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], name=op.f('fk_governance_authorities_jurisdiction_id_jurisdictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_governance_authorities'))
    )
    op.create_table('iiot_edge_sync_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('payload_size_bytes', sa.Integer(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('sync_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_iiot_edge_sync_logs_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_iiot_edge_sync_logs'))
    )
    op.create_index(op.f('ix_iiot_edge_sync_logs_device_id'), 'iiot_edge_sync_logs', ['device_id'], unique=False)
    op.create_table('methodologies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ui_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('form_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['methodology_families.id'], name=op.f('fk_methodologies_family_id_methodology_families'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registry_id'], ['methodology_registries.id'], name=op.f('fk_methodologies_registry_id_methodology_registries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodologies'))
    )
    op.create_index(op.f('ix_methodologies_code'), 'methodologies', ['code'], unique=True)
    op.create_table('registry_sync_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['registry_id'], ['registry_configs.id'], name=op.f('fk_registry_sync_logs_registry_id_registry_configs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registry_sync_logs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_registry_sync_logs_idempotency_key'))
    )
    op.create_table('sensor_definitions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('metadata_id', sa.UUID(), nullable=False),
    sa.Column('local_identifier', sa.String(length=100), nullable=False),
    sa.Column('calibration_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sensor_definitions_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metadata_id'], ['sensor_metadata.id'], name=op.f('fk_sensor_definitions_metadata_id_sensor_metadata')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_definitions'))
    )
    op.create_index(op.f('ix_sensor_definitions_device_id'), 'sensor_definitions', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_definitions_metadata_id'), 'sensor_definitions', ['metadata_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('requires_password_change', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('evidence_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('file_uri', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_evidence_records_uploaded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_evidence_records_verified_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_records'))
    )
    op.create_table('methodology_dependencies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('methodology_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('dependency_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodologies.id'], name=op.f('fk_methodology_dependencies_methodology_id_methodologies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_dependencies'))
    )
    op.create_index(op.f('ix_methodology_dependencies_methodology_id'), 'methodology_dependencies', ['methodology_id'], unique=False)
    op.create_table('methodology_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('methodology_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('retirement_date', sa.Date(), nullable=True),
    sa.Column('migration_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodologies.id'], name=op.f('fk_methodology_versions_methodology_id_methodologies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_versions'))
    )
    op.create_index(op.f('ix_methodology_versions_methodology_id'), 'methodology_versions', ['methodology_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('properties',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sustainability_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_properties_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_properties_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties'))
    )
    op.create_index(op.f('ix_properties_organization_id'), 'properties', ['organization_id'], unique=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_uri', sa.String(length=500), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reports_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_table('telemetry_streams',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('stream_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_telemetry_streams_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor_definitions.id'], name=op.f('fk_telemetry_streams_sensor_id_sensor_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_streams'))
    )
    op.create_index(op.f('ix_telemetry_streams_device_id'), 'telemetry_streams', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_streams_sensor_id'), 'telemetry_streams', ['sensor_id'], unique=False)
    op.create_table('methodology_legacy_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_code', sa.String(length=100), nullable=False),
    sa.Column('methodology_version_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], name=op.f('fk_methodology_legacy_mappings_methodology_version_id_methodology_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_legacy_mappings'))
    )
    op.create_index(op.f('ix_methodology_legacy_mappings_legacy_code'), 'methodology_legacy_mappings', ['legacy_code'], unique=True)
    op.create_table('methodology_workflows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['methodology_versions.id'], name=op.f('fk_methodology_workflows_version_id_methodology_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_workflows'))
    )
    op.create_index(op.f('ix_methodology_workflows_version_id'), 'methodology_workflows', ['version_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('methodology_id', sa.UUID(), nullable=False),
    sa.Column('methodology_version_id', sa.UUID(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('registry_id', sa.String(), nullable=True),
    sa.Column('baseline_source', sa.String(length=30), nullable=True),
    sa.Column('diesel_emission_factor', sa.Float(), nullable=True),
    sa.Column('grid_emission_factor', sa.Float(), nullable=True),
    sa.Column('crediting_start', sa.Date(), nullable=True),
    sa.Column('crediting_end', sa.Date(), nullable=True),
    sa.Column('baseline_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], name=op.f('fk_projects_jurisdiction_id_jurisdictions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodologies.id'], name=op.f('fk_projects_methodology_id_methodologies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], name=op.f('fk_projects_methodology_version_id_methodology_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['climate_programmes.id'], name=op.f('fk_projects_programme_id_climate_programmes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_jurisdiction_id'), 'projects', ['jurisdiction_id'], unique=False)
    op.create_index(op.f('ix_projects_methodology_id'), 'projects', ['methodology_id'], unique=False)
    op.create_index(op.f('ix_projects_methodology_version_id'), 'projects', ['methodology_version_id'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_programme_id'), 'projects', ['programme_id'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_table('telemetry_payloads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('stream_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['telemetry_streams.id'], name=op.f('fk_telemetry_payloads_stream_id_telemetry_streams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_payloads'))
    )
    op.create_index(op.f('ix_telemetry_payloads_stream_id'), 'telemetry_payloads', ['stream_id'], unique=False)
    op.create_index(op.f('ix_telemetry_payloads_timestamp'), 'telemetry_payloads', ['timestamp'], unique=False)
    op.create_table('version_calculation_rules',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['methodology_calculation_rules.id'], name=op.f('fk_version_calculation_rules_rule_id_methodology_calculation_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['methodology_versions.id'], name=op.f('fk_version_calculation_rules_version_id_methodology_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'rule_id', name=op.f('pk_version_calculation_rules'))
    )
    op.create_table('version_evidence_templates',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['methodology_evidence_templates.id'], name=op.f('fk_version_evidence_templates_template_id_methodology_evidence_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['methodology_versions.id'], name=op.f('fk_version_evidence_templates_version_id_methodology_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'template_id', name=op.f('pk_version_evidence_templates'))
    )
    op.create_table('version_monitoring_templates',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['methodology_monitoring_templates.id'], name=op.f('fk_version_monitoring_templates_template_id_methodology_monitoring_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['methodology_versions.id'], name=op.f('fk_version_monitoring_templates_version_id_methodology_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'template_id', name=op.f('pk_version_monitoring_templates'))
    )
    op.create_table('version_reporting_templates',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['methodology_reporting_templates.id'], name=op.f('fk_version_reporting_templates_template_id_methodology_reporting_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['methodology_versions.id'], name=op.f('fk_version_reporting_templates_version_id_methodology_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'template_id', name=op.f('pk_version_reporting_templates'))
    )
    op.create_table('version_validation_rules',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['methodology_validation_rules.id'], name=op.f('fk_version_validation_rules_rule_id_methodology_validation_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['methodology_versions.id'], name=op.f('fk_version_validation_rules_version_id_methodology_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'rule_id', name=op.f('pk_version_validation_rules'))
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assets_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_assets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_asset_type_id'), 'assets', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_assets_organization_id'), 'assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_table('methodology_workflow_stages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('required_role', sa.String(length=100), nullable=True),
    sa.Column('abac_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('escalation_timer_hours', sa.Integer(), nullable=True),
    sa.Column('escalation_webhook', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['methodology_workflows.id'], name=op.f('fk_methodology_workflow_stages_workflow_id_methodology_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_workflow_stages'))
    )
    op.create_index(op.f('ix_methodology_workflow_stages_workflow_id'), 'methodology_workflow_stages', ['workflow_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('gps_accuracy', sa.Float(), nullable=True),
    sa.Column('environment_type', sa.String(length=10), nullable=True),
    sa.Column('radius_used_m', sa.Float(), nullable=True),
    sa.Column('duplicate_flag', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('trust_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('validation_hash', sa.String(length=64), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('evidence_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_activities_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_activities_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_activities_property_id_properties'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'organization_id', 'created_at', name=op.f('pk_activities'))
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_asset_id'), 'activities', ['asset_id'], unique=False)
    op.create_index(op.f('ix_activities_client_id'), 'activities', ['client_id'], unique=False)
    op.create_index(op.f('ix_activities_image_hash'), 'activities', ['image_hash'], unique=False)
    op.create_index(op.f('ix_activities_organization_id'), 'activities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_activities_property_id'), 'activities', ['property_id'], unique=False)
    op.create_index(op.f('ix_activities_status'), 'activities', ['status'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_table('digital_twins',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('twin_status', sa.String(length=50), nullable=False),
    sa.Column('state_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_digital_twins_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_digital_twins_device_id_devices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_digital_twins'))
    )
    op.create_index(op.f('ix_digital_twins_asset_id'), 'digital_twins', ['asset_id'], unique=True)
    op.create_index(op.f('ix_digital_twins_device_id'), 'digital_twins', ['device_id'], unique=True)
    op.create_table('methodology_workflow_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('schema_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['methodology_workflow_stages.id'], name=op.f('fk_methodology_workflow_tasks_stage_id_methodology_workflow_stages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_workflow_tasks'))
    )
    op.create_index(op.f('ix_methodology_workflow_tasks_stage_id'), 'methodology_workflow_tasks', ['stage_id'], unique=False)
    op.create_table('digital_twin_states',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('digital_twin_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['digital_twin_id'], ['digital_twins.id'], name=op.f('fk_digital_twin_states_digital_twin_id_digital_twins'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_digital_twin_states'))
    )
    op.create_index(op.f('ix_digital_twin_states_digital_twin_id'), 'digital_twin_states', ['digital_twin_id'], unique=False)
    op.create_index(op.f('ix_digital_twin_states_timestamp'), 'digital_twin_states', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digital_twin_states_timestamp'), table_name='digital_twin_states')
    op.drop_index(op.f('ix_digital_twin_states_digital_twin_id'), table_name='digital_twin_states')
    op.drop_table('digital_twin_states')
    op.drop_index(op.f('ix_methodology_workflow_tasks_stage_id'), table_name='methodology_workflow_tasks')
    op.drop_table('methodology_workflow_tasks')
    op.drop_index(op.f('ix_digital_twins_device_id'), table_name='digital_twins')
    op.drop_index(op.f('ix_digital_twins_asset_id'), table_name='digital_twins')
    op.drop_table('digital_twins')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_status'), table_name='activities')
    op.drop_index(op.f('ix_activities_property_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_organization_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_image_hash'), table_name='activities')
    op.drop_index(op.f('ix_activities_client_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_asset_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_methodology_workflow_stages_workflow_id'), table_name='methodology_workflow_stages')
    op.drop_table('methodology_workflow_stages')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_organization_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('version_validation_rules')
    op.drop_table('version_reporting_templates')
    op.drop_table('version_monitoring_templates')
    op.drop_table('version_evidence_templates')
    op.drop_table('version_calculation_rules')
    op.drop_index(op.f('ix_telemetry_payloads_timestamp'), table_name='telemetry_payloads')
    op.drop_index(op.f('ix_telemetry_payloads_stream_id'), table_name='telemetry_payloads')
    op.drop_table('telemetry_payloads')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_programme_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_methodology_version_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_methodology_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_jurisdiction_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_methodology_workflows_version_id'), table_name='methodology_workflows')
    op.drop_table('methodology_workflows')
    op.drop_index(op.f('ix_methodology_legacy_mappings_legacy_code'), table_name='methodology_legacy_mappings')
    op.drop_table('methodology_legacy_mappings')
    op.drop_index(op.f('ix_telemetry_streams_sensor_id'), table_name='telemetry_streams')
    op.drop_index(op.f('ix_telemetry_streams_device_id'), table_name='telemetry_streams')
    op.drop_table('telemetry_streams')
    op.drop_table('reports')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_organization_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_methodology_versions_methodology_id'), table_name='methodology_versions')
    op.drop_table('methodology_versions')
    op.drop_index(op.f('ix_methodology_dependencies_methodology_id'), table_name='methodology_dependencies')
    op.drop_table('methodology_dependencies')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sensor_definitions_metadata_id'), table_name='sensor_definitions')
    op.drop_index(op.f('ix_sensor_definitions_device_id'), table_name='sensor_definitions')
    op.drop_table('sensor_definitions')
    op.drop_table('registry_sync_logs')
    op.drop_index(op.f('ix_methodologies_code'), table_name='methodologies')
    op.drop_table('methodologies')
    op.drop_index(op.f('ix_iiot_edge_sync_logs_device_id'), table_name='iiot_edge_sync_logs')
    op.drop_table('iiot_edge_sync_logs')
    op.drop_table('governance_authorities')
    op.drop_table('emission_factor_libraries')
    op.drop_table('compliance_frameworks')
    op.drop_table('climate_programmes')
    op.drop_table('verification_tasks')
    op.drop_table('validation_bodies')
    op.drop_index(op.f('ix_trust_logs_activity_id'), table_name='trust_logs')
    op.drop_table('trust_logs')
    op.drop_table('signatures')
    op.drop_table('sensor_metadata')
    op.drop_table('registry_configs')
    op.drop_table('registry_adapters')
    op.drop_table('protocol_definitions')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_methodology_validation_rules_code'), table_name='methodology_validation_rules')
    op.drop_table('methodology_validation_rules')
    op.drop_index(op.f('ix_methodology_reporting_templates_code'), table_name='methodology_reporting_templates')
    op.drop_table('methodology_reporting_templates')
    op.drop_index(op.f('ix_methodology_registries_code'), table_name='methodology_registries')
    op.drop_table('methodology_registries')
    op.drop_table('methodology_packages')
    op.drop_index(op.f('ix_methodology_monitoring_templates_code'), table_name='methodology_monitoring_templates')
    op.drop_table('methodology_monitoring_templates')
    op.drop_index(op.f('ix_methodology_families_code'), table_name='methodology_families')
    op.drop_table('methodology_families')
    op.drop_index(op.f('ix_methodology_evidence_templates_code'), table_name='methodology_evidence_templates')
    op.drop_table('methodology_evidence_templates')
    op.drop_index(op.f('ix_methodology_calculation_rules_code'), table_name='methodology_calculation_rules')
    op.drop_table('methodology_calculation_rules')
    op.drop_table('marketplace_listings')
    op.drop_index(op.f('ix_jurisdictions_code'), table_name='jurisdictions')
    op.drop_table('jurisdictions')
    op.drop_table('financial_transactions')
    op.drop_index(op.f('ix_emission_factor_registry_country'), table_name='emission_factor_registry')
    op.drop_index(op.f('ix_emission_factor_registry_code'), table_name='emission_factor_registry')
    op.drop_table('emission_factor_registry')
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_compliance_runs_project_id'), table_name='compliance_runs')
    op.drop_table('compliance_runs')
    op.drop_table('audit_trails')
    op.drop_table('audit_reports')
    # ### end Alembic commands ###
