export const FEATURE_FLAGS = {
  ENABLE_DIGITAL_TWINS: process.env.NEXT_PUBLIC_ENABLE_DIGITAL_TWINS === "true",
  ENABLE_VERIFIED_REGISTRY_SYNC: process.env.NEXT_PUBLIC_ENABLE_VERIFIED_REGISTRY_SYNC === "true",
  ENABLE_LIVE_IOT: process.env.NEXT_PUBLIC_ENABLE_LIVE_IOT === "true",
  ENABLE_ARTICLE6: process.env.NEXT_PUBLIC_ENABLE_ARTICLE6 === "true",
  ENABLE_SCADA: process.env.NEXT_PUBLIC_ENABLE_SCADA === "true",
  ENABLE_VERRA_SYNC: process.env.NEXT_PUBLIC_ENABLE_VERRA_SYNC === "true",
  ENABLE_GOLD_STANDARD_SYNC: process.env.NEXT_PUBLIC_ENABLE_GOLD_STANDARD_SYNC === "true",
  ENABLE_AI_INSIGHTS: process.env.NEXT_PUBLIC_ENABLE_AI_INSIGHTS === "true",
  ENABLE_SATELLITE_MONITORING: process.env.NEXT_PUBLIC_ENABLE_SATELLITE_MONITORING === "true",
};
